In [2]:
# NUMPY
# INTRODUCTION OF NUMPY :>
# Numpy is an opern -source library of python which is used for handle scintific -calculation.

In [4]:
pip install numpy
# pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
# why numpy is better then list 
# 1. numpy is homogenous data type and list is a hetrogenious data type.
# 2. numpy take less memory while list take more.
# 3. numpy take less excution time while list take more excution time.
# 4. numpy has more functionality as compare to the list.

In [10]:
import numpy as np

In [12]:
a=[1,2,3,4]
type(a)

list

In [16]:
b=np.array(a)
b

array([1, 2, 3, 4])

In [18]:
type(b)

numpy.ndarray

In [20]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b= np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print("total Rows and Coloum:",b.shape)  # shape=number(rows) ,n(coloum)
print("Total Elements:",b.size)  # size=n(row)*n(coloum)
print("total dimension:",b.ndim)  # ndmi stands for n_dimension here =(x,y)

total Rows and Coloum: (3, 3)
Total Elements: 9
total dimension: 2


In [26]:
# USER DEFINE ARRAY 

a=[]
size=int(input("enter the size:"))
for i in range(size):
    val=int(input("enter items:"))
    a.append(val)

b= np.array(a)
b

enter the size: 3
enter items: 5
enter items: 4
enter items: 5


array([5, 4, 5])

In [28]:
# FUNCTIONS IN NUMPY

In [30]:
# 1. ZERO()...> iw will create an array in which all the values will be 0 in either one-dimension
# or multiple-dimension.


In [32]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [36]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
# 2. ONES()...> it will create an array in which all the values will be 1 either one 
# dimision or multi-dimension

In [40]:
a=np.ones(3)
a

array([1., 1., 1.])

In [42]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
# 3. EYE()...> it will create an array in which diganl positional elements will be 1 
# and rest all are 0(zero).


In [46]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [48]:
# 4. DIAG()...> we can set custom values on digonal position.

In [50]:
a=np.array([10,34,67,90])
a

array([10, 34, 67, 90])

In [52]:
b=np.diag(a)
b

array([[10,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

In [56]:
# 5. RANDOM MODULE...>
# (A) RANDIT()....> it will generate randome number in a given range.

a=np.random.randint(1,10,3)
a

array([3, 2, 3])

In [58]:
# (B) RAND()...> it will generate number in range 0-1.
a=np.random.rand(4)
a

array([0.91246327, 0.2755612 , 0.15273596, 0.98971444])

In [60]:
# (C) SEED...> it iwll fix our random generate data.

np.random.seed(55)
a=np.random.randint(1,10,3)
a

array([8, 9, 6])

In [62]:
# OPERATIONS ON ARRAY

a=np.random.randint(1,50,12)
a

array([38, 28, 34, 49, 36, 47, 31, 14, 31, 13, 25, 48])

In [64]:
a.size

12

In [66]:
# 12====> reshape
# 1*12, 12*1
# 2*6, 6*2
# 3*4 , 4*3

# total =36
# 1*36, 36*1
# 2*18, 18*2
# 3*12, 12*3


In [68]:
a.reshape(2,6)

array([[38, 28, 34, 49, 36, 47],
       [31, 14, 31, 13, 25, 48]])

In [70]:
a.reshape(3,4)

array([[38, 28, 34, 49],
       [36, 47, 31, 14],
       [31, 13, 25, 48]])

In [72]:
a.reshape(4,3)

array([[38, 28, 34],
       [49, 36, 47],
       [31, 14, 31],
       [13, 25, 48]])

In [77]:
# OPERATION ON ARRAY
# reshaping the array 

In [79]:
a= np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [81]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [83]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [85]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [87]:
a=a.reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [89]:
np.sum(a)  # total sum

120

In [91]:
np.sum(a,axis=0)  # colom wise sum(axis=0 i numpy)

array([35, 40, 45])

In [93]:
np.sum(a,axis=1)  # row wise sum

array([ 6, 15, 24, 33, 42])

In [95]:
a= np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [97]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [99]:
a+b

array([[ 6,  8],
       [10, 12]])

In [101]:
a-b

array([[-4, -4],
       [-4, -4]])

In [103]:
a*b # matrix multiply is not this

array([[ 5, 12],
       [21, 32]])

In [105]:
a.dot(b)  # dot () we can multliply of matrix.

array([[19, 22],
       [43, 50]])

In [107]:
a=np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16])

In [109]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [111]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [113]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])