In [2]:
# NUMPY DAY 2....>
# UNIQUE METHOD....> IT WILL RETURN 3 ARRAYS / unique ()
# arr....> uniquw element of array.
# return_index= TRUE ...> return indexing of unique elements.
# Return_count= TRUE...> return frequency of unique element.

In [6]:
import numpy as np

In [8]:
a=np.array([1,2,3,4,1,1,1,5,6,7])
a

array([1, 2, 3, 4, 1, 1, 1, 5, 6, 7])

In [10]:
np.unique(a, return_index=True , return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7]),
 array([0, 1, 2, 3, 7, 8, 9], dtype=int64),
 array([4, 1, 1, 1, 1, 1, 1], dtype=int64))

In [18]:
# LINSPACE()...> it will create an array in which gap of values will be eqal.
# syntax : np.linspace(min,max,total_number)

In [20]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
# HSTACK (horizontal) ...> it will combine all the arrays horizontally.
# VSTACK (vertical)...> it will combine all the arrays vertically.

In [36]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

In [38]:
np.hstack((a,b,c)) # it will combine horizontally

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.vstack((a,b,c))  #  it will combine vertically

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# PANDAS : Pandas is a open-source library of python thats is used for handle data maniuplation. 

In [50]:
# pip intall pamndas ( for intallation
!pip install pandas

In [52]:
import pandas as pd

In [54]:
# DATA STRUCTURE OF PANDAS :
# (A)...> SERIES = it is one-dimensional arrays it shoows onnly values.
# (B)....> DATAFRAME = it is multi-dimensional array and it contains values with colum name.

In [64]:
# (A) SERIES :

a= pd.Series([1,54,22,36,7,8])
a

0     1
1    54
2    22
3    36
4     7
5     8
dtype: int64

In [66]:
type(a)

pandas.core.series.Series

In [85]:
# (B) Dataframe :

a={
    "Emp_id":[1,2,3,4,5],
    "Name":['sam','raj','harsh','aman','shivam'],
    "Department":['It','Cse','Doctor','Cs','Teacher'],
    "Salary":[100,200,30000,400,500]
}
df=pd.DataFrame(a)
df

Emp_id    Name Department  Salary
0       1     sam         It     100
1       2     raj        Cse     200
2       3   harsh     Doctor   30000
3       4    aman         Cs     400
4       5  shivam    Teacher     500

In [91]:
df.to_csv("C:\\Users\\harsh\\OneDrive\\Desktop\\PANDAS\\emp_info.csv",index=False)